# Vagrantfile per Rocky Linux 9
Vagrant.configure("2") do |config|
  # Box ufficiale Rocky Linux 9
  config.vm.box = "rockylinux/9"

  # Nome della VM
  config.vm.hostname = "otel-lab"

  # Rete privata con IP fisso (modifica se serve)
  #config.vm.network "private_network", ip: "192.168.56.50"
  config.vm.network "forwarded_port", guest: 5000, host: 5000     # Flask
  config.vm.network "forwarded_port", guest: 9090, host: 9090     # Prometheus
  config.vm.network "forwarded_port", guest: 3000, host: 3000     # Grafana
  config.vm.network "forwarded_port", guest: 9464, host: 9464     # OTel Collector
  config.vm.network "forwarded_port", guest: 16686, host: 16686   # Jaeger (opzionale)
 
  #per gestione file
  config.vm.synced_folder ".", "/vagrant"

  # Risorse hardware
  config.vm.provider "virtualbox" do |vb|
    #vb.name = "rocky-t6-vm"
    vb.memory = "2048"   # almeno 2GB
    vb.cpus = 2
  end

  # Provisioning di base (aggiornamenti + utilità comuni)
  config.vm.provision "shell", inline: <<-SHELL
    sudo dnf -y update
    sudo dnf -y install curl wget git vim
  SHELL
end

